routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('/search', 'HomeController@search');
Route::get('/property/{id}', 'PropertyController@show');

Route::group(['middleware'=>['auth','member']], function(){
    Route::get('/profile', 'AccountController@profile');
    Route::post('profileupdate','AccountController@profileupdate');
    Route::resource('properties', 'PropertyController');
});

Auth::routes();

app/Models/Property.php
<?php

namespace App\Models;

use App\Comment;
use App\Rating;
use Illuminate\Database\Eloquent\Model;

class Property extends Model
{
    protected $fillable = [
    	'title',    'price',        'featured',     'purpose',      'type',       
        'bedroom',      'bathroom',     'city',     'address',      'area',
        'description',  'video',        'floor_plan',   'location_latitude', 'location_longitude',   'nearby',
    ];

    public function user()
    {
    	return $this->belongsTo(User::class);
    }
    
    public function features()
    {
    	return $this->belongsToMany(Feature::class, 'property_features');
    }

    public function propertyImages()
    {
    	return $this->hasMany(PropertyImage::class);
    }

    public function ratings()
    {
    	return $this->hasMany(Rating::class);
    }

    public function listings()
    {
        return $this->hasMany(Listing::class);
    }
    
    public function comments()
    {
    	return $this->morphMany(Comment::class, 'commentable');
    }
}

app/Http/Controllers/PropertyController.php
<?php
namespace App\Http\Controllers;

use App\Models\Property;
use App\Services\FeatureService;
use App\Services\PropertyService;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class PropertyController extends Controller
{
    public function index(PropertyService $ps)
    {
        $prps = $ps->findAll();
        
        return view('properties.index',compact('prps'));
    }

    public function show($id, PropertyService $ps)
    {
        $prp = $ps->find($id);
        
        return view('properties.show', compact('prp'));
    }
    
    public function create(PropertyService $ps, FeatureService $fs)
    {   
        $feas = $fs->findAll();

        return view('properties.create',compact('feas'));
    }

    public function edit($id, PropertyService $ps, FeatureService $fs)
    {
        $feas = $fs->findAll();
        $prp = $ps->find($id);

        return view('properties.edit',compact('prp','feas'));
    }
    
    public function store(Request $request, PropertyService $ps) 
    { 
        $this->validateProperty($request);
        
        $image = $request->file('image');
        $imagename = null;
        if (isset($image)) {
            $imagename = $this->imageToDisk($image, $request->title);
        }

        $ps->saveNew($request->all(), $request->features, $imagename);

        toastr()->success('Property created successfully');
        return redirect()->route('properties.index');
    }

    public function update($id, Request $request, PropertyService $ps)
    {   
        $this->validateProperty($request);
        
        $image = $request->file('image');
        $imagename = null;
        if (isset($image)) {
            $imagename = $this->imageToDisk($image, $request->title);
        }
        
        $ps->update($id, $request->all(), $request->features, $imagename);
        
        toastr()->success('Property updated successfully');
        return redirect()->route('properties.index');
    }

    public function destroy(Property $property)
    {
        $property = Property::find($property->id);

        if(Storage::disk('public')->exists('property/'.$property->image)){
            Storage::disk('public')->delete('property/'.$property->image);
        }
        if(Storage::disk('public')->exists('property/'.$property->floor_plan)){
            Storage::disk('public')->delete('property/'.$property->floor_plan);
        }

        $property->delete();
        $property->features()->detach();
        
        toastr()->success('Property deleted successfully');
        return back();
    }

    private function validateProperty(Request $request)
    {
        $request->validate([
            'title'     => 'required|max:255',
            'price'     => 'required',
            'purpose'   => 'required',
            'type'      => 'required',
            'bedroom'   => 'required',
            'bathroom'  => 'required',
            'city'      => 'required',
            'address'   => 'required',
            'area'      => 'required',
            'image'     => 'image|mimes:jpeg,jpg,png',
            'floor_plan'=> 'image|mimes:jpeg,jpg,png',
            'description'        => 'required',
            'location_latitude'  => 'required',
            'location_longitude' => 'required'
        ]);
    }
    
    private function imageToDisk($image, $title)
    {
        $currentDate = Carbon::now()->toDateString();
        $imagename = Str::slug($title).'-'.$currentDate.'-'.uniqid().'.'.$image->getClientOriginalExtension();
        
        if(!Storage::disk('public')->exists('property')){
            dd($title);
            Storage::disk('public')->makeDirectory('property');
        }

        $propertyimage = Image::make($image)->save();
        Storage::disk('public')->put('property/'.$imagename, $propertyimage);
        
        return $imagename;
    }
}

resources/views/properties/create.blade.php
@extends('layouts.app')

@section('styles')

@endsection

@section('content')

    <section class="section">
        <div class="container">
            <div class="row">

                <div class="col s12 m3">
                    <div class="agent-sidebar">
                        @include('agent.sidebar')
                    </div>
                </div>

                <div class="col s12 m9">
                    <div class="agent-content">
                        <h4 class="agent-title">CREATE PROPERTY</h4>

                        <form action="{{route('agent.properties.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">title</i>
                                    <input id="title" name="title" type="text" class="validate" data-length="200">
                                    <label for="title">Title</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                    <i class="material-icons prefix">monetization_on</i>
                                    <input id="price" name="price" type="number" class="validate">
                                    <label for="price">Price</label>
                                </div>
                                <div class="input-field col s6">
                                    <i class="material-icons prefix">business</i>
                                    <input id="area" name="area" type="number" class="validate">
                                    <label for="area">Floor Area</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                    <i class="material-icons prefix">airline_seat_flat</i>
                                    <input id="bedroom" name="bedroom" type="number" class="validate">
                                    <label for="bedroom">Bedroom</label>
                                </div>
                                <div class="input-field col s6">
                                    <i class="material-icons prefix">event_seat</i>
                                    <input id="bathroom" name="bathroom" type="number" class="validate">
                                    <label for="bathroom">Bathroom</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s4">
                                    <i class="material-icons prefix">location_city</i>
                                    <input id="city" name="city" type="text" class="validate">
                                    <label for="city">City</label>
                                </div>
                                <div class="input-field col s8">
                                    <i class="material-icons prefix">account_balance</i>
                                    <textarea id="address" name="address" class="materialize-textarea"></textarea>
                                    <label for="address">Address</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s3">
                                    <p>
                                        <label>
                                            <input type="checkbox" name="featured" class="filled-in" checked="checked" />
                                            <span>Featured</span>
                                        </label>
                                    </p>
                                </div>
                                <div class="input-field col s9">
                                    <i class="material-icons prefix">mode_edit</i>
                                    <textarea id="description" name="description" class="materialize-textarea"></textarea>
                                    <label for="description">Description</label>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col s3">
                                    <label class="label-custom" for="type">Property Type</label>
                                    <p>
                                        <label>
                                            <input class="with-gap" name="type" value="house" type="radio"  />
                                            <span>Sale</span>
                                        </label>
                                    <p>
                                    </p>
                                        <label>
                                            <input class="with-gap" name="type" value="apartment" type="radio"  />
                                            <span>Rent</span>
                                        </label>
                                    </p>
                                </div>
                                <div class="col s3">
                                    <label class="label-custom" for="purpose">Property Purpose</label>
                                    <p>
                                        <label>
                                            <input class="with-gap" name="purpose" value="sale" type="radio"  />
                                            <span>House</span>
                                        </label>
                                    <p>
                                    </p>
                                        <label>
                                            <input class="with-gap" name="purpose" value="rent" type="radio"  />
                                            <span>Apartment</span>
                                        </label>
                                    </p>
                                </div>
                                <div class="input-field col s6">
                                    <select multiple name="features[]">
                                        <option value="" disabled selected>Choose Features</option>
                                        @foreach($features as $feature)
                                            <option value="{{ $feature->id }}">{{ $feature->name }}</option>
                                        @endforeach
                                    </select>
                                    <label class="label-custom">Select Features</label>
                                </div>
                            </div>

                            <div class="row">
                                <div class="file-field input-field col s12">
                                    <div class="btn indigo">
                                        <span>Featured Image</span>
                                        <input type="file" name="image">
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path validate" type="text">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s6">
                                    <i class="material-icons prefix">map</i>
                                    <input id="location_latitude" name="location_latitude" type="text" class="validate">
                                    <label for="location_latitude">Latitude</label>
                                </div>
                                <div class="input-field col s6">
                                    <i class="material-icons prefix">map</i>
                                    <input id="location_longitude" name="location_longitude" type="text" class="validate">
                                    <label for="location_longitude">Longitude</label>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">voice_chat</i>
                                    <input id="video" name="video" type="text" class="validate">
                                    <label for="video">Youtube Link</label>
                                </div>
                            </div>

                            <div class="row">
                                <div class="file-field input-field col s12">
                                    <div class="btn indigo">
                                        <span>Floor Plan</span>
                                        <input type="file" name="floor_plan">
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path validate" type="text">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s12">
                                    <i class="material-icons prefix">place</i>
                                    <textarea id="nearby" name="nearby" class="materialize-textarea"></textarea>
                                    <label for="nearby">Nearby</label>
                                </div>
                            </div>

                            <div class="row">
                                <div class="file-field input-field col s12">
                                    <div class="btn indigo">
                                        <span>Upload Gallery Images</span>
                                        <input type="file" name="gallaryimage[]" multiple>
                                        <span class="helper-text" data-error="wrong" data-success="right">Upload one or more images</span>
                                    </div>
                                    <div class="file-path-wrapper">
                                        <input class="file-path validate" type="text" placeholder="Upload one or more images">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col s12 m-t-30">
                                    <button class="btn waves-effect waves-light btn-large indigo darken-4" type="submit">
                                        Submit
                                        <i class="material-icons right">send</i>
                                    </button>
                                </div>
                            </div>

                        </form>


                    </div>
                </div> <!-- /.col -->

            </div>
        </div>
    </section>

@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        $('input#title, textarea#nearby').characterCounter();
        $('select').formSelect();
    });

</script>
@endsection

resources/views/properties/index.blade.php
@extends('layouts.app')

@section('styles')
@endsection

@section('content')

    <section class="section">
        <div class="container">
            <div class="row">

                <div class="col s12 m3">
                    <div class="agent-sidebar">
                        SIDEBAR GOES HERE
                    </div>
                </div>

                <div class="col s12 m9">

                    <h4 class="agent-title">PROPERTY LIST</h4>
                    
                    <div class="agent-content">
                        <table class="striped responsive-table">
                            <thead>
                                <tr>
                                    <th>SL.</th>
                                    <th>Title</th>
                                    <th>Type</th>
                                    <th>City</th>
                                    <th><i class="material-icons small-star p-t-10">comment</i></th>
                                    <th><i class="material-icons small-star p-t-10">stars</i></th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                    
                            <tbody>
                                @foreach( $prps as $key => $prp )
                                    <tr>
                                        <td class="right-align">{{$key+1}}.</td>
                                        <td>
                                            <span class="tooltipped" data-position="bottom" data-tooltip="{{$prp->title}}">
                                                {{ Str::limit($prp->title, 30) }}
                                            </span>
                                        </td>
                                        
                                        <td>{{ ucfirst($prp->type) }}</td>
                                        <td>{{ ucfirst($prp->city) }}</td>

                                        <td class="center">
                                            <span><i class="material-icons small-comment left">comment</i>{{ $prp->comments_count }}</span>
                                        </td>

                                        <td class="center">
                                            @if($prp->featured == true)
                                                <span class="indigo-text"><i class="material-icons small-star">stars</i></span>
                                            @endif
                                        </td>
    
                                        <td class="center">
                                            <a href="properties/{{ $prp->id }}" target="_blank" class="btn btn-small green waves-effect">
                                                <i class="material-icons">visibility</i>
                                            </a>
                                            <a href="properties/{{ $prp->id }}/edit" class="btn btn-small orange waves-effect">
                                                <i class="material-icons">edit</i>
                                            </a>
                                            <button type="button" class="btn btn-small deep-orange accent-3 waves-effect" onclick="deleteProperty({{$prp->id}})">
                                                <i class="material-icons">delete</i>
                                            </button>
                                            <form action="properties/{{ $prp->id }}" method="POST" id="del-property-{{$prp->id}}" style="display:none;">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="center">
                            Render links to following pages
                        </div>
                    </div>
        
                </div>

            </div>
        </div>
    </section>

@endsection

@section('scripts')
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        function deleteProperty(id){
            swal({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            buttons: true,
            dangerMode: true,
            buttons: ["Cancel", "Yes, delete it!"]
            }).then((value) => {
                if (value) {
                    document.getElementById('del-property-'+id).submit();
                    swal(
                    'Deleted!',
                    'Property has been deleted.',
                    'success',
                    {
                        buttons: false,
                        timer: 1000,
                    })
                }
            })
        }
    </script>
@endsection